spring:
  # Mysql
  datasource:
      url: jdbc:mysql://localhost:3306/db_quartz?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: pass1234

  # Quartz
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: marcus.malcomm@gmail.com
    password: gmail@29144138
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#org:
#  quartz:
#    jobStore:
#      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate